"""Parameter-efficient fine-tuning modules."""

from .base import PEFTModuleMixin
from .adapters import (
    AdaptFormerAdapter,
    AdaptFormerBlock,
    AdaptFormerConfig,
    AdapterBankConfig,
    AdapterConfig,
    AdapterFusion,
    AdapterFusionConfig,
    AdapterRecipe,
    BottleneckAdapter,
    ConvPassAdapter,
    ConvPassBlock,
    ConvPassConfig,
    OrthogonalLinear,
    OrthogonalAdapterConfig,
    OutputAdapterModule,
    ParallelAdapterConfig,
    ParallelAdapterBlock,
    RepAdapterConfig,
    RepAdapterLinear,
    SerialAdapterBlock,
    add_adapter,
    adapter_fusion_trainable_spec,
    apply_adapters,
    apply_adaptformer,
    apply_adapter_fusion,
    apply_convpass,
    apply_orthogonal_adapters,
    apply_repadapter,
    configure_adapter_bank,
    extract_adapter_delta,
    iter_adapter_wrappers,
    iter_orthogonal_adapters,
    iter_repadapters,
    load_adapter_delta,
    merge_orthogonal_adapters,
    merge_repadapters,
    set_active_adapter,
    strip_adapters,
    unmerge_orthogonal_adapters,
    unmerge_repadapters,
)
from .bitfit import BitFitConfig, bitfit_trainable_spec
from .dora import DoRAConfig, DoRALinear, DoRAMergedLinear, DoRARecipe, apply_dora, merge_dora
from .ia3 import IA3Config, IA3Linear, apply_ia3, iter_ia3_modules, merge_ia3
from .lora import (
    AdaLoRAConfig,
    AdaLoRAMetadata,
    AdaLoRAModule,
    CalibrationSpec,
    EVAInitializerConfig,
    FourierFTConfig,
    FourierFTLinear,
    LoftQConfig,
    LoRAConfig,
    LoRAFAConfig,
    LoRAFALinear,
    LoRALinear,
    LoRAMergedLinear,
    LoRAPlusLabelConfig,
    LoRARecipe,
    PiSSAConfig,
    QuantizedBaseLoRACompatibility,
    QuantizerSpec,
    RandLoRAConfig,
    RandLoRALinear,
    RsLoRAConfig,
    StaticRankMaskedLoRAConfig,
    apply_adalora,
    apply_eva_lora,
    apply_fourierft,
    apply_loftq_lora,
    apply_lora,
    apply_lora_fa,
    apply_lora_rank_pattern,
    apply_randlora,
    extract_lora_delta,
    iter_fourierft_modules,
    iter_lora_fa_modules,
    iter_lora_modules,
    iter_randlora_modules,
    load_lora_delta,
    loftq_quantization_fingerprint,
    merge_lora,
    merge_fourierft,
    merge_lora_fa,
    merge_randlora,
    lora_rank_groups,
    strip_lora,
    validate_loftq_lora,
    unmerge_fourierft,
    unmerge_lora,
    unmerge_lora_fa,
    unmerge_randlora,
)
from .prefix import (
    PrefixAttention,
    PrefixConfig,
    PrefixProjection,
    PrefixTunedModel,
    apply_prefixes,
)
from .prompts import (
    PTuningV2Config,
    PromptConfig,
    PromptedModel,
    SoftPromptConfig,
    VPTDeepConfig,
    VPTDeepRecipe,
    VPTShallowConfig,
    VPTShallowRecipe,
    apply_prompts,
)
from .scale_shift import (
    ScaleShift,
    ScaleShiftConfig,
    ScaleShiftWrapper,
    apply_scale_shift,
    iter_scale_shift_wrappers,
    merge_scale_shift,
)
from .side_tuning import (
    ActivationTap,
    LSTConfig,
    LadderConnection,
    SideNetwork,
    SideTunedModel,
    apply_side_tuning,
    iter_side_tuned_models,
    strip_side_tuning,
)
from .vera import VeRAConfig, VeRALinear, apply_vera, iter_vera_modules, merge_vera, strip_vera

PEFTConfig = (
    LoRAConfig
    | DoRAConfig
    | AdapterConfig
    | ConvPassConfig
    | OrthogonalAdapterConfig
    | RepAdapterConfig
    | RandLoRAConfig
    | PromptConfig
    | PrefixConfig
    | ScaleShiftConfig
    | IA3Config
    | VeRAConfig
    | LSTConfig
)

__all__ = (
    "ActivationTap",
    "AdaptFormerAdapter",
    "AdaptFormerBlock",
    "AdaptFormerConfig",
    "AdapterBankConfig",
    "AdapterConfig",
    "AdapterFusion",
    "AdapterFusionConfig",
    "AdapterRecipe",
    "AdaLoRAConfig",
    "AdaLoRAMetadata",
    "AdaLoRAModule",
    "BitFitConfig",
    "BottleneckAdapter",
    "CalibrationSpec",
    "ConvPassAdapter",
    "ConvPassBlock",
    "ConvPassConfig",
    "DoRAConfig",
    "DoRALinear",
    "DoRAMergedLinear",
    "DoRARecipe",
    "IA3Config",
    "IA3Linear",
    "LSTConfig",
    "LadderConnection",
    "EVAInitializerConfig",
    "FourierFTConfig",
    "FourierFTLinear",
    "LoftQConfig",
    "LoRAConfig",
    "LoRAFAConfig",
    "LoRAFALinear",
    "LoRALinear",
    "LoRAMergedLinear",
    "LoRAPlusLabelConfig",
    "LoRARecipe",
    "PEFTModuleMixin",
    "PEFTConfig",
    "PTuningV2Config",
    "PiSSAConfig",
    "OrthogonalLinear",
    "OrthogonalAdapterConfig",
    "OutputAdapterModule",
    "ParallelAdapterConfig",
    "ParallelAdapterBlock",
    "PrefixAttention",
    "PrefixConfig",
    "PrefixProjection",
    "PrefixTunedModel",
    "PromptConfig",
    "PromptedModel",
    "QuantizedBaseLoRACompatibility",
    "QuantizerSpec",
    "RandLoRAConfig",
    "RandLoRALinear",
    "RepAdapterConfig",
    "RepAdapterLinear",
    "RsLoRAConfig",
    "StaticRankMaskedLoRAConfig",
    "ScaleShift",
    "ScaleShiftConfig",
    "ScaleShiftWrapper",
    "SerialAdapterBlock",
    "SideNetwork",
    "SideTunedModel",
    "SoftPromptConfig",
    "VPTDeepConfig",
    "VPTDeepRecipe",
    "VPTShallowConfig",
    "VPTShallowRecipe",
    "VeRAConfig",
    "VeRALinear",
    "add_adapter",
    "adapter_fusion_trainable_spec",
    "apply_adapters",
    "apply_adaptformer",
    "apply_adapter_fusion",
    "apply_adalora",
    "apply_convpass",
    "apply_dora",
    "apply_eva_lora",
    "apply_fourierft",
    "apply_ia3",
    "apply_loftq_lora",
    "apply_lora",
    "apply_lora_fa",
    "apply_lora_rank_pattern",
    "apply_orthogonal_adapters",
    "apply_randlora",
    "apply_repadapter",
    "apply_prefixes",
    "apply_prompts",
    "apply_scale_shift",
    "apply_vera",
    "apply_side_tuning",
    "bitfit_trainable_spec",
    "configure_adapter_bank",
    "extract_adapter_delta",
    "extract_lora_delta",
    "iter_adapter_wrappers",
    "iter_fourierft_modules",
    "iter_lora_fa_modules",
    "iter_lora_modules",
    "iter_randlora_modules",
    "iter_orthogonal_adapters",
    "iter_repadapters",
    "iter_ia3_modules",
    "iter_scale_shift_wrappers",
    "iter_vera_modules",
    "iter_side_tuned_models",
    "load_adapter_delta",
    "load_lora_delta",
    "loftq_quantization_fingerprint",
    "lora_rank_groups",
    "merge_fourierft",
    "merge_dora",
    "merge_ia3",
    "merge_lora",
    "merge_lora_fa",
    "merge_orthogonal_adapters",
    "merge_randlora",
    "merge_repadapters",
    "merge_scale_shift",
    "merge_vera",
    "set_active_adapter",
    "strip_lora",
    "strip_adapters",
    "strip_vera",
    "strip_side_tuning",
    "unmerge_fourierft",
    "unmerge_lora",
    "unmerge_lora_fa",
    "unmerge_orthogonal_adapters",
    "unmerge_randlora",
    "unmerge_repadapters",
    "validate_loftq_lora",
)
