from pathlib import Path

import jax
import jax.numpy as jnp
import jax.random as jr
import numpy as np
import pytest

import equimo.audio.models as am
from equimo.registry import get_model_cls


KEY = jr.PRNGKey(0)
NUM_CLASSES = 10
SPEC = jr.normal(KEY, (64, 32))
DATA_DIR = Path(__file__).parent / "data"


def _small_ast(**kwargs):
    cfg = {
        "input_fdim": 32,
        "input_tdim": 64,
        "dim": 32,
        "patch_size": 16,
        "fstride": 16,
        "tstride": 16,
        "num_heads": 4,
        "depths": [1],
        "num_classes": NUM_CLASSES,
        "key": KEY,
    }
    cfg.update(kwargs)
    return am.AudioSpectrogramTransformer(**cfg)


def test_ast_forward():
    model = _small_ast()
    y = model(SPEC, key=KEY, inference=True)

    assert y.shape == (NUM_CLASSES,)
    assert jnp.all(jnp.isfinite(y))


def test_ast_cls_patch_mean_global_pool():
    model = _small_ast(global_pool="cls_patch_mean", head_norm_layer="layernorm")
    y = model(SPEC, key=KEY, inference=True)

    assert model.head.in_features == 64
    assert y.shape == (NUM_CLASSES,)
    assert jnp.all(jnp.isfinite(y))


def test_ast_features_and_aux_shapes():
    model = _small_ast()
    features = model.features(SPEC, key=KEY, inference=True)
    aux = model.forward_features(SPEC, key=KEY, inference=True)

    assert model.grid_size == (2, 4)
    assert model.num_patches == 8
    assert features.shape == (10, 32)
    assert aux["x_norm_cls_token"].shape == (32,)
    assert aux["x_norm_dist_token"].shape == (32,)
    assert aux["x_norm_patchtokens"].shape == (8, 32)
    assert aux["x_prenorm"].shape == (10, 32)
    assert jnp.all(jnp.isfinite(features))


def test_ast_batching_with_vmap():
    model = _small_ast()
    batch = jr.normal(KEY, (3, 64, 32))

    y = jax.vmap(lambda x: model(x, key=KEY, inference=True))(batch)

    assert y.shape == (3, NUM_CLASSES)
    assert jnp.all(jnp.isfinite(y))


def test_ast_factory_forward_with_overrides():
    model = am.ast_tiny_patch16_224(
        input_fdim=32,
        input_tdim=64,
        dim=32,
        fstride=16,
        tstride=16,
        num_heads=4,
        depths=[1],
        num_classes=NUM_CLASSES,
        key=KEY,
    )
    y = model(SPEC, key=KEY, inference=True)

    assert y.shape == (NUM_CLASSES,)
    assert jnp.all(jnp.isfinite(y))


def test_ast_unsupported_pretrained_variant_raises():
    with pytest.raises(ValueError, match="Supported AST pretrained variants"):
        am.ast_base_patch16_224(pretrained=True)


@pytest.mark.parametrize(
    ("factory", "reference_name"),
    [
        (
            am.ast_base_patch16_audioset_10_10_0_4593,
            "ast_base_patch16_audioset_10_10_0_4593_reference.npz",
        ),
        (
            am.ast_base_patch16_speechcommands_v2_10_10_0_9812,
            "ast_base_patch16_speechcommands_v2_10_10_0_9812_reference.npz",
        ),
    ],
)
def test_ast_pretrained_matches_hf(factory, reference_name):
    """Converted AST weights must match Hugging Face features and logits.

    Reference values are generated by `models/ast.py` from the matching
    `MIT/ast-*` Hugging Face checkpoints.
    """
    ref = np.load(DATA_DIR / reference_name)
    x = jnp.asarray(ref["input_values"])
    model = factory(pretrained=True)

    fwd = model.forward_features(x, key=KEY, inference=True)
    logits = model(x, key=KEY, inference=True)

    cls_mae = float(
        np.mean(np.abs(np.array(fwd["x_norm_cls_token"]) - ref["cls_token"]))
    )
    dist_mae = float(
        np.mean(np.abs(np.array(fwd["x_norm_dist_token"]) - ref["dist_token"]))
    )
    logits_mae = float(np.mean(np.abs(np.array(logits) - ref["logits"])))

    assert cls_mae < 5e-4, f"AST cls token MAE vs Hugging Face: {cls_mae:.2e}"
    assert dist_mae < 5e-4, f"AST dist token MAE vs Hugging Face: {dist_mae:.2e}"
    assert logits_mae < 5e-4, f"AST logits MAE vs Hugging Face: {logits_mae:.2e}"


def test_audio_ast_registered_by_modality():
    assert get_model_cls("ast", modality="audio") is am.AudioSpectrogramTransformer


def test_ast_wrong_input_size_raises():
    model = _small_ast()

    with pytest.raises(AssertionError, match="time dimension"):
        model(jnp.ones((65, 32)), key=KEY, inference=True)

    with pytest.raises(AssertionError, match="frequency dimension"):
        model(jnp.ones((64, 33)), key=KEY, inference=True)
